### PR TITLE
New Fluent configuration API

### PR DESCRIPTION
**Pull request by tsimbalar**
This PR introduces a new fluent API for configuration (related to issue #51).

The starting point for the configuration is `SerilogWebClassic.Configuration` and its chainable/fluent methods which allow configuration such as : 

```csharp
SerilogWebClassic.Configuration
	.UseLogger(myCustomLogger)
	.LogAtLevel(LogEventLevel.Debug)
	.IgnoreRequestsMatching(ctx => !ctx.Request.IsAuthenticated)
	.EnableFormDataLogging(formData => formData
			.AtLevel(LogEventLevel.Debug)
			.OnlyOnError()
			.FilterKeywords(new[] {"password", "authToken"} )
	);
```

The documentation in the README has been updated.
It introduces tests that cover both the *old* static API and the new Fluent one to make sure no regression is introduced.
The *old* APIs have been marked as *obsolete*, and delegates internally to the new ones.

I would love to get some feedback on the code, of course, but also on the naming of the classes and methods, so that *SerilogWeb* gives a better developer experience (the same way Serilog does)

### CODE REVIEW

**Comment by nblumhardt** [comment]
Looking good!

Perhaps, since it's so closely related to Serilog, it could use the same builder/init pattern?

```csharp
SerilogWeb.Configuration = new SerilogWebConfigurationBuilder()
	.UseLogger(myCustomLogger)
	.LogAtLevel(LogEventLevel.Debug)
	.IgnoreRequestsMatching(ctx => !ctx.Request.IsAuthenticated)
	.EnableFormDataLogging(formData => formData
			.AtLevel(LogEventLevel.Debug)
			.OnlyOnError()
			.FilterKeywords(new[] {"password", "authToken"} )
	)
        .Build();
```

Or some variant.. the nice thing here being that the returned "configuration" can be immutable and thus thread-safe, instead of needing to deal with mutation on-the-fly. What do you think?

**Comment by tsimbalar** [comment]
That makes sense !  I'll try going in that direction.

**Comment by tsimbalar** [comment]
After some more thinking, I'm afraid introducing a builder here would make the configuration API harder to discover and use (mostly the end user would need to know about the existence of the `*Builder` class) , and the combination of Configuration and Builder in the same name does not quite roll off the tongue :).

How about : 
```csharp
SerilogWebClassic.Configure(cfg =>
	.UseLogger(myCustomLogger)
	.LogAtLevel(LogEventLevel.Debug)
	.IgnoreRequestsMatching(ctx => !ctx.Request.IsAuthenticated)
	.EnableFormDataLogging(formData => formData
			.AtLevel(LogEventLevel.Debug)
			.OnlyOnError()
			.FilterKeywords(new[] {"password", "authToken"} )
	)
)
```

In that snippet, `cfg` is actually a builder, and each call to a fluent method returns that builder, updated... We just don't ask the user for a `new Builder(...)` , and it also allows to hide the `Configuration` class altogether (also `Configuration` could be made immutable). 

Another approach would be to make the `Configuration` class immutable and have each *configuration method* return a new instance, but then the end user would still need to remember to assign that configuration back to the static property : 

```csharp
SerilogWeb.Configuration = new SerilogWebConfiguration()
	.UseLogger(myCustomLogger)
	.LogAtLevel(LogEventLevel.Debug)
	.IgnoreRequestsMatching(ctx => !ctx.Request.IsAuthenticated)
	.EnableFormDataLogging(formData => formData
			.AtLevel(LogEventLevel.Debug)
			.OnlyOnError()
			.FilterKeywords(new[] {"password", "authToken"} )
	);
```

The code to support that would be a bit trickier, C# is not so great for this kind of immutable cases where we want a new instance, similar to the previous except 1 or 2 properties (F# anyone ? ;) )

**Comment by nblumhardt** [comment]
First option looks fine (both look good to me) - afraid I'm low on time to be much use generating ideas :-) .. will defer to your tastes here 👍

**Review by nblumhardt — APPROVED** [review]

**Comment by tsimbalar** [comment]
The `Configuration` object is now immutable to make it all thread-safe. 

The consequence is also that `SerilogWebClassic.Configuration` may have been reassigned between the time the requests *is recorded* and the time the log event is produced, so the reference to it cannot be kept by `WebRequestLoggingHandler` ... not a big deal, but it did break all the tests for a moment :P 

The `README` is up-to-date : [see rendered](https://github.com/tsimbalar/classic/blob/be42d3fb7511c6129157533f709037125929dcae/README.md) and the API looks like : 

```csharp
SerilogWebClassic.Configure(cfg => 
  .UseLogger(myCustomLogger)
  .LogAtLevel(LogEventLevel.Debug)
  .IgnoreRequestsMatching(ctx => !ctx.Request.IsAuthenticated)
  .EnableFormDataLogging(forms => forms
    .AtLevel(LogEventLevel.Debug)
    .OnlyOnError()
    .FilterKeywords(new[] {"password", "authToken"} )
));
```

The previous API is marked as obsolete.

**Pull request merged**
