### PR TITLE
trap for ASP.NET integrated mode (resolves:1)

### PR DESCRIPTION
**Pull request by brettveenstra**

### CODE REVIEW

**Comment by nblumhardt** [comment]
Thank you for the PR, sorry about the slow response. Just a couple of thoughts:
- If the exception doesn't match the test, shoudl we re-`throw`?
- Formatting - seems like indentation has gone wrong somewhere in there? Braces etc. in the diff are misaligned
- Does/should this apply to any other enrichers that use `HttpContext`?
- Should we write the exception to `SelfLog` "just in case"?

Cheers!

**Comment by IanYates** [comment]
The accessing of HttpContext.Current.Request throwing an exception (rather than returning the expected null) is really frustrating.  I often debug without "Just My Code" turned on so I can step into some other sources (or decompile if need be).  

Reading up on this I see from http://mvolo.com/iis7-integrated-mode-request-is-not-available-in-this-context-exception-in-applicationstart/ and http://stackoverflow.com/a/23401984/1053381 that this is a known problem.  The only way around it is either poking around using reflection or using some app-global state to know when we're in a request by perhaps setting some "I am in a request" flag on HttpContext itself.  

Is there a nice way for us to hook begin/end request from a NuGet package?  Alternatively, could we extend serilog-web with a method to set the flag on HttpContext (which we'd call from begin request in global.asax.cs), and a configuration switch to tell this library to check for that flag's presence?

**Comment by nblumhardt** [comment]
@brettveenstra hi - it's been a couple of weeks since you submitted this one - are you keen to complete it? Happy to help from here, thanks again for the PR!

**Comment by brettveenstra** [comment]
Been slammed.  Won't get to this for a few more weeks I'm afraid.  

BTW: I did a quick and dirty cut of the Loggly sink for dotnet40.  Let me know if you're interested in those edits or if it's too old to bother...

---

**Comment by konste** [comment]
I see a ton of those noisy HttpExceptions and very much want them to go away. 
This is the link to .net code which causes trouble: http://referencesource.microsoft.com/#System.Web/HttpContext.cs,920 

Unfortunately there is no good way to get rid of those exceptions in Serilog.
One way is to catch and ignore those as @brettveenstra proposed. No need to check exception text – only one kind of exceptions may come out of get_Request property. Also no need to pollute SelfLog with it. 

Another way would be to access it through reflection (there is a field _request) and I would consider rather safe (although dirty, of course).

Third way is to set a flag per HttpContext when Request is available, but IMHO it is too involved for the purpose. 

HttpContext.Current.Request is used all over SerilogWeb.Classic and I believe all of them should be fixed. 

Nick, let me know which way you prefer and I try to find time and send PR next week. I never ever send any PR before, so bear with me.

For now I have to disable web enrichment altogether as it is way too noisy.

Konstantin

**Comment by nblumhardt** [comment]
Hi @konste - thanks for the offer of help, much appreciated. I'm happy with the `try ... catch` version, it seems the least likely to be a maintenance problem over time (unlike setting flags or using reflection). I also agree we shouldn't pollute `SelfLog` with these.

The nicest option for me would be something like:

``` csharp
HttpRequest request;
if (CurrentHttpContext.TryGetRequest(out request))
{
   // Do the enrichment
}
```

where `CurrentHttpContext` is a helper class shared across the codebase. What do you think?

Regards,
Nick

**Comment by konste** [comment]
We definitely would need shared common helper class. The question is how shared? Which source file (or folder, if it should be separate file) is suitable for it?

I don't like TryGetRequest because it makes usages of the class cumbersome and there are plenty.

We have many places like this:
HttpContext.Current.Request == null

How about we introduce helper class HttpContextCurrent with the same semantic:
HttpContextCurrent.Request == null

Usages would look almost like now (one dot skipped), but it would handle possible exception and return null as the clients expect in case it is unavailable.

I don't want to replace one liner with multiline construct.

Agree?

Konstantin
(sent from mobile device)

On Jul 4, 2015, at 3:57 PM, Nicholas Blumhardt <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi @konstehttps://github.com/konste - thanks for the offer of help, much appreciated. I'm happy with the try ... catch version, it seems the least likely to be a maintenance problem over time (unlike setting flags or using reflection). I also agree we shouldn't pollute SelfLog with these.

The nicest option for me would be something like:

HttpRequest request;
if (CurrentHttpContext.TryGetRequest(out request))
{
   // Do the enrichment
}

where CurrentHttpContext is a helper class shared across the codebase. What do you think?

Regards,
Nick

##

**Comment by nblumhardt** [comment]
Yep, `HttpContextCurrent.Request` looks good to me too. :+1:

**Comment by nblumhardt** [comment]
This one was fixed via #9 - thanks again for kicking it off @brettveenstra :-)

**Pull request closed without merging**
